// frontend/src/app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./common/Footer";
import Header from "@/app/common/Header";
import { Toaster } from "sonner";
import { Loader } from "@/components/Loader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Loader />
        <Toaster richColors />
        {/* <Header /> */}
        <main>{children}</main>
        <Footer /> {/* Include the Footer component here */}
      </body>
    </html>
  );
}
